[test]
# Allow @tests/ path alias in test command
preload = ["./tests/apps/api/setup.ts"]

[run]
# Support for path aliases
# @tests/ will resolve to ./tests/

[install]
# Use exact versions
exact = true

[alias]
"@api" = "./apps/api/src"
